config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
    resources :accounts
  end
  resources :transactions
  resources :adjustments
  resources :accounts
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :flows, only: [:show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  match '/empty_day', to: 'transactions#empty_day'
  root to: 'static_pages#home'  
  match '/inspect', to: 'static_pages#inspect'
  match '/fv', to: 'static_pages#fv'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_cash.html.erb
<h3>Available Income: <a id="incomeVal" rel="popover" data-content="$<%= @cashValue %>" data-original-title="BOOST" value="<%= @cash %>" cash="<%= @cash %>"><%= number_to_currency(@cash, options={:precision=>0})%></a> <% if @cashValue>0 %>(BOOSTED)<% end %> (Updated <%= @check_acct.created_at.strftime('%b. %e, %Y') %>)
<div id="incomeBoostSpan">BOOST:<span class="add-on">$</span><%= text_field_tag 'incomeBoost', nil, :placeholder=>@cashValue, :class=> 'input-mini', :id=>'incomeBoost' %><span class="add-on">.00</span> <%= button_tag 'Save', :id=>'saveIncome', :class=>'btn btn-medium btn-success' %> <%= button_tag 'Cancel', :id=>'cancelIncome', :class=>'btn btn-medium btn-warning' %> <div id="slider"></div></div></h3>
<div class="progress" expense-value="<%= @spending_sum+@adjustment_sum %>" >
  <div class="bar <%=@cash_bar%>" id="incomeBar" style="width: <%= ((Float(@cash)/@total)*100)-0.1 %>%;" value="<%= @cash %>" max-value="<%= @total %>"></div> <!-- -0.1% to keep bar from sliding -->
  <%=link_to adjustments_path do %><div class="bar expense bar-warning" id="adjustBar" style="width: <%=Float(@adjustment_sum.abs)/@total*100 %>%;" rel="popover" data-content="$<%= @adjustment_sum.to_i %>" data-original-title="Monthly Drain"></div><% end %>
  <% @flow_sum.each {|key, value| if value>0 %>
    <% @flow=Flow.where(:id=>key).first %>
    <%=link_to(@flow) do %><div class="bar expense <%=@flow.name %>" style="width: <%= (value/@total)*100 %>%;" rel="popover" data-content="$<%= value.to_i %>" data-original-title="<%= @flow.name %>"></div><% end %>
  <% end } %>
</div>

app/views/shared/_debt.html.erb
<% debt_percent=(Float(debt.balance)/debt.initial_balance)*100 %>
<h3><%= debt.name %>: <span id="debtBalance" balance="<%= debt.balance %>"><%= number_to_currency(debt.balance, options={:precision=>0}) %></span></h3>
<% colour="%06x" % (rand * 0xffffff) %>
<div class="progress">
  <div class="bar" id="debtBar" style="width: <%= debt_percent %>%; background-color: #<%=colour%>; background-image:none;" total="<%= debt.initial_balance %>" ></div>
</div>

app/views/shared/_debt_display.html.erb
<li>
  <%= debt_display.name %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_flow_form.html.erb
<div class="flow_field">
<%= form_for Flow.new, :remote => 'true' do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name, 'Name of New Flow' %>
    <%= f.text_field :name %>
    <%= f.label :description, 'Description of New Flow' %>
    <%= f.text_field :description %>
    <%= f.submit "Add New Flow", class: "btn btn-large btn-primary" %>
<% end %>
<%= render @flows %>
</div>

app/views/shared/_flow_question.html.erb
<% unless flow_question.name=="Income" %>
<li id="<%= flow_question.id %>" class="<%=flow_question.name%>">
  <span class="question_content">
    <h3 class="flowHeader"><%= flow_question.name %></h3>
    <% transaction=@transactions.where('flow_id=? AND transaction_date=?', flow_question.id, @day).first %>
    <% if transaction %>
       <% transaction_value=transaction.value.round %>
       <% transaction_desc=transaction.description %>
    <% else %>
      <% transaction_value=0 %>
    <% end %>
    <span class="input-prepend input-append">
      <span class="add-on">$</span><%= text_field_tag 'value', nil, :placeholder=>transaction_value, :class=> 'input-medium flow-input', :id=>'input_'+flow_question.id.to_s, :tabindex=>1 %><span class="add-on">.00</span>
    </span>
    <%= button_tag 'N', :id=>'note_button'+flow_question.id.to_s, :class=>'note_button btn btn-large btn-success', :tabindex=>2 %>
    <% if transaction_desc %>
      <%= text_area_tag nil, transaction_desc, :id=>'notes'+flow_question.id.to_s, :class=>'note_area', :style=>'display:inline' %>
    <% else %>
      <%= text_area_tag nil, transaction_desc, :id=>'notes'+flow_question.id.to_s, :class=>'note_area' %>
    <% end %>
  </span>
</li>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    <%= f.submit "Post", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/shared/_question_form_header.html.erb
<span class="question_header">
  <h3>Daily Questionnaire - 
    <% if(!@day.today?()) %>
      <span class='highlight_date' id='date_tag' date='<%= @day %>'>
    <% else %>
      <span class='today_date' id='date_tag' date='<%= @day %>'>
    <% end %>
    <%= link_to '<<', root_path(:date=>@day-1) %>
    <%= @day.strftime('%A, %b. %e, %Y') %>
    </span>
    <%= link_to_unless(@day.today?(), '>>', root_path(:date=>@day+1)) %>
    <%= link_to_unless(@day.today?(), '>|', root_path(:date=>Date.current())) %>
    <%= submit_tag "No Flows", class: "btn btn-small btn-primary", id: "no_expense_btn" %>
  </h3>
</span>
<%= render 'cash' %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<span class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</span>

app/views/shared/_transaction_form.html.erb
<div class="center_flow">
  <span>FLOW</span>
  <section>
      <%= render 'shared/flow_form' %>
  </section>
<%= form_for @transaction, :html=> {:class=>'form-inline'} do |t| %>
  <%= collection_select(:transaction, :flow_id, @flows, :id, :name) %>
  <%= button_tag(:type=>'button', :id=>'toggle_new_flow', :class=> 'btn') do %>+<% end %><br/>
  <%= t.date_select :transaction_date, options = {:end_year=> Time.now.year, :use_short_month=>true, :order=>[:day, :month, :year]}, class: "input-small" %>
  <div class="input-prepend input-append">
    <span class="add-on">$</span><%= t.number_field :value, :class=> 'input-medium', :placeholder=>'Value', :options => {:min=>'0'} %><span class="add-on">.00</span>
  </div>
  <%= t.submit "New", class: "btn" %>
<% end %>
</div>

<script type="text/javascript">
$('.flow_field').toggle();
$('#toggle_new_flow').click(function(){
  $('.flow_field').toggle();
  $("label[for='transaction_Flow']").toggle();
  $("#transaction_flow_id").toggle();
  if($('#toggle_new_flow').text() == '+') $('#toggle_new_flow').text('-');
  else $('#toggle_new_flow').text('+');
});
</script>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1>
  <%= current_user.name %>
</h1>